const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;
const NO_CONTENT = 204;
const REDIRECTED = 301;
const FOUND = 302;
const NOT_MODIFIED = 304;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const PAYMENT_REQUIRED = 402;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 405;
const NOT_ACCEPTABLE = 406;
const REQUEST_TIMEOUT = 408;
const CONFLICT = 409;
const GONE = 410;
const LENGTH_REQUIRED = 411;
const PAYLOAD_TOO_LARGE = 413;
const URI_TOO_LONG = 414;
const UNSUPPORTED_MEDIA_TYPE = 415;
const EXPECTATION_FAILED = 417;
const FAILED_DEPENDENCY = 424;
const TOO_EARLY = 425;
const UPGRADE_REQUIRED = 426;
const TOO_MANY_REQUESTS = 429;
const REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
const UNAVAILABLE_FOR_LEGAL_REASONS = 451;

const INTERNAL_SERVER_ERROR = 500;
const SERVER_ERROR = 500; // For backward compatibility
const NOT_IMPLEMENTED = 501;
const BAD_GATEWAY = 502;
const SERVICE_UNAVAILABLE = 503;
const GATEWAY_TIMEOUT = 504;
const HTTP_VERSION_NOT_SUPPORTED = 505;
const INSUFFICIENT_STORAGE = 507;
const BANDWIDTH_LIMIT_EXCEEDED = 509;
const NETWORK_AUTHENTICATION_REQUIRED = 511;

export {
	OK,
	CREATED,
	ACCEPTED,
	NO_CONTENT,
	REDIRECTED,
	FOUND,
	NOT_MODIFIED,
	BAD_REQUEST,
	UNAUTHORIZED,
	FORBIDDEN,
	NOT_FOUND,
	METHOD_NOT_ALLOWED,
	NOT_ACCEPTABLE,
	CONFLICT,
	FAILED_DEPENDENCY,
	SERVER_ERROR,
	BAD_GATEWAY,
	SERVICE_UNAVAILABLE,
	GATEWAY_TIMEOUT,
	HTTP_VERSION_NOT_SUPPORTED,
	UNSUPPORTED_MEDIA_TYPE,
	LENGTH_REQUIRED,
	PAYLOAD_TOO_LARGE,
	URI_TOO_LONG,
	EXPECTATION_FAILED,
	TOO_EARLY,
	UPGRADE_REQUIRED,
	TOO_MANY_REQUESTS,
	REQUEST_TIMEOUT,
	REQUEST_HEADER_FIELDS_TOO_LARGE,
	UNAVAILABLE_FOR_LEGAL_REASONS,
	INSUFFICIENT_STORAGE,
	BANDWIDTH_LIMIT_EXCEEDED,
	NETWORK_AUTHENTICATION_REQUIRED,
	PAYMENT_REQUIRED,
	GONE,
	INTERNAL_SERVER_ERROR,
	NOT_IMPLEMENTED,
};
