replicaCount: 1

ingress:
  enabled: true
  host: auth.dev.medlink.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

env:
  DB_HOST: psql-medlink-dev.postgres.database.azure.com
  DB_NAME: medlink
  DB_USER: medlinkadmin
  MAIL_SERVER_SMTP_HOST: smtp.zoho.com
  MAIL_SERVER_AUTH_MAIL: hello@medlink.com
  MAIL_SERVER_NOREPLY_MAIL: hello@medlink.com

autoscaling:
  enabled: false

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

externalSecret:
  name: auth-service-secrets-dev

keyVault:
  enabled: true
  name: kv-medlink-dev
  tenantId: 562608dd-cd22-47d6-8eb4-6e9eba231422
  clientId: 7271016c-082b-43e1-aa6a-3030dda01fb7    
