{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVault.clientId }}
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}
    objects: |
      array:
        - |
          objectName: db-pass
          objectType: secret
        - |
          objectName: jwt-secret-key
          objectType: secret
        - |
          objectName: app-paseto-key
          objectType: secret
        - |
          objectName: cookie-identifier
          objectType: secret
        - |
          objectName: cookie-keys
          objectType: secret
        - |
          objectName: mail-auth-pass
          objectType: secret
        - |
          objectName: mail-noreply-pass
          objectType: secret
        - |
          objectName: google-client-id
          objectType: secret
        - |
          objectName: google-client-secret
          objectType: secret
        - |
          objectName: fb-app-id
          objectType: secret
        - |
          objectName: fb-app-secret
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.externalSecret.name }}
      type: Opaque
      data:
        - objectName: db-pass
          key: DB_PASS
        - objectName: jwt-secret-key
          key: JWT_SECRET_KEY
        - objectName: app-paseto-key
          key: APP_PASETO_KEY
        - objectName: cookie-identifier
          key: COOKIE_IDENTIFIER
        - objectName: cookie-keys
          key: COOKIE_KEYS
        - objectName: mail-auth-pass
          key: MAIL_SERVER_AUTH_PASS
        - objectName: mail-noreply-pass
          key: MAIL_SERVER_NOREPLY_PASS
        - objectName: google-client-id
          key: googleID
        - objectName: google-client-secret
          key: googleSECRET
        - objectName: fb-app-id
          key: fbID
        - objectName: fb-app-secret
          key: fbSECRET
{{- end }}
