name: Auth Service CD

on:
  push:
  #   branches:
  #       - main
  # # pull_request:
  # #   branches:
  # #       - main
  # #       - feature/* az aks get-credentials -g medlink-dev-rg -n aks-medlink-dev
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  Auth-Service-CD-Dev:
    uses: Medlink-Ehealth/pipeline-templates/.github/workflows/shared-cd.yml@main
    with:
      cluster-name: 'aks-medlink-dev'
      resource-group: 'medlink-dev-rg'
      namespace: 'dev'
      release-name: 'auth-service-dev'
      chart-path: './apps/auth-service/helm'
      values-file: './apps/auth-service/helm/values.dev.yaml'
      image-repository: 'crmedlinkdev001.azurecr.io/auth-service'
      image-tag: 'latest'
    secrets: inherit