name: Auth Service CI

on:
#   push:
#     branches:
#         - main
  # pull_request:
  #   branches:
  #       - main
  #       - feature/*
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  Auth-Service-ci:
    uses: Medlink-Ehealth/pipeline-templates/.github/workflows/shared-ci.yml@main
    with:
      dockerfile-path: './apps/auth-service/Dockerfile'
      working-directory: './apps/auth-service'
      acr-login-server: 'crmedlinkdev001'
      image-name: 'auth-service'
    secrets: inherit
