name: Auth Service CD

on:
  push:
    branches:
        - main
        - feature/*
  pull_request:
    branches:
        - main
        - feature/*
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  Auth-Service-CD-Dev:
    uses: Medlink-Ehealth/pipeline-templates/.github/workflows/shared-cd.yml@main
    with:
      cluster-name: 'aks-medlink-dev-001'
      resource-group: 'rg-medlink-dev'
      release-name: 'auth-service-dev'
      chart-path: './apps/auth-service/helm'
      image-repository: 'crmedlinkdev001.azurecr.io/auth-service'
    secrets: inherit