name: APIM VNet Deployment

on:
  push:
    branches:
        - main
        - feature/*
  pull_request:
    branches:
        - main
        - feature/*
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  Auth-Service-ci:
    uses: Medlink-Ehealth/pipeline-templates/.github/workflows/shared-ci.yml@feature/setup-pipeline
    with:
      working-directory: './apps/auth-service'
      dockerfile-path: './apps/auth-service/Dockerfile'
      docker-context: '.'
      acr-login-server: 'crmedlinkdev'
      image-name: 'auth-service'
    secrets: inherit